version: '3'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=bcda
      - POSTGRES_PASSWORD=toor
    ports:
      - "5430:5432"
    volumes:
      - ./db:/var/db
  documentation:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.ssas
      target: documentation
    volumes:
      - .:/go/src/github.com/CMSgov/bcda-ssas-app
  ssas:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.ssas
      args:
        VERSION: latest
    image: bcda-ssas:latest
    environment:
      - DATABASE_URL=postgresql://postgres:toor@db:5432/bcda?sslmode=disable
      - ATO_PUBLIC_KEY_FILE=../shared_files/ATO_public.pem
      - ATO_PRIVATE_KEY_FILE=../shared_files/ATO_private.pem
      - HTTP_ONLY=true
      - BCDA_AUTH_PROVIDER=${BCDA_AUTH_PROVIDER}
      - BCDA_SSAS_CLIENT_ID=${BCDA_SSAS_CLIENT_ID}
      - BCDA_SSAS_SECRET=${BCDA_SSAS_SECRET}
      - DEPLOYMENT_TARGET=local
      - SKIP_BOOTSTRAP=true
      - SSAS_ADMIN_SIGNING_KEY_PATH=../shared_files/ssas/admin_test_signing_key.pem
      - SSAS_PUBLIC_SIGNING_KEY_PATH=../shared_files/ssas/public_test_signing_key.pem
      - SSAS_ADMIN_PORT=:3004
      - SSAS_PUBLIC_PORT=:3003
      - SSAS_HTTP_TO_HTTPS_PORT=:3005
      - SSAS_HASH_ITERATIONS=130000
      - SSAS_HASH_KEY_LENGTH=64
      - SSAS_HASH_SALT_SIZE=32
      - SSAS_TOKEN_DENYLIST_CACHE_CLEANUP_MINUTES=15
      - SSAS_TOKEN_DENYLIST_CACHE_TIMEOUT_MINUTES=1440
      - SSAS_TOKEN_DENYLIST_CACHE_REFRESH_MINUTES=5
      - SSAS_CLIENT_ASSERTION_AUD=http://local.testing.cms.gov/api/v2/Token/auth
    volumes:
      - ./shared_files:/usr/local/shared_files
      - .:/go/src/github.com/CMSgov/bcda-ssas-app
    ports:
      - "3103:3003"
      - "3104:3004"
      - "3105:3005"
    depends_on:
      - db
