version: '3'

services:
  localstack-unit-test:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=wafv2
      - DEBUG=1
    volumes:
      - "./.localstack_volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: 'curl --silent --fail localstack-unit-test:4566/_localstack/health | grep -E ''"s3": "(available|running)"'''
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  tests:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.tests
      args:
        VERSION: latest
    environment:
      # Set default values for Localstack to work
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-foobar}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-foobar}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      # other env vars
      - DB=postgresql://postgres:toor@db:5432
      - DATABASE_URL=postgresql://postgres:toor@db:5432/bcda?sslmode=disable
      - BCDA_SSAS_CLIENT_ID=fake-client-id
      - BCDA_SSAS_SECRET=fake-secret
      - ENV=local
      - DEPLOYMENT_TARGET=local
      - SSAS_ADMIN_SIGNING_KEY_PATH=../../../shared_files/ssas/admin_test_signing_key.pem
      - SSAS_PUBLIC_SIGNING_KEY_PATH=../../../shared_files/ssas/public_test_signing_key.pem
      - SSAS_PUBLIC_PORT=:3003
      - SSAS_ADMIN_PORT=:3004
      - SSAS_HTTP_TO_HTTPS_PORT=:3005
      - SSAS_HASH_ITERATIONS=130000
      - SSAS_HASH_KEY_LENGTH=64
      - SSAS_HASH_SALT_SIZE=32
      - SSAS_TOKEN_DENYLIST_CACHE_CLEANUP_MINUTES=15
      - SSAS_TOKEN_DENYLIST_CACHE_TIMEOUT_MINUTES=1440
      - SSAS_TOKEN_DENYLIST_CACHE_REFRESH_MINUTES=5
      - SSAS_URL=http://ssas:3004
      - SSAS_PUBLIC_URL=http://ssas:3003
      - SSAS_CLIENT_ASSERTION_AUD=http://local.testing.cms.gov/api/v2/Token/auth
    volumes:
      - .:/go/src/github.com/CMSgov/bcda-ssas-app
    depends_on:
      localstack-unit-test:
        condition: service_healthy
  postman_test:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.postman_test
    volumes:
      - .:/go/src/github.com/CMSgov/bcda-ssas-app
  smoke_test_ssas:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.postman_test
    volumes:
      - .:/go/src/github.com/CMSgov/bcda-ssas-app
