FROM golang:1.24.4-alpine3.22

RUN apk update upgrade && apk add \
    bash \
    build-base \
    curl

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.2.1

RUN go install github.com/xo/usql@v0.17.5
RUN go install github.com/securego/gosec/v2/cmd/gosec@v2.22.5
RUN go install gotest.tools/gotestsum@v1.12.0
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.15.2

WORKDIR /go/src/github.com/CMSgov/bcda-ssas-app
COPY . .

WORKDIR /go/src/github.com/CMSgov/bcda-ssas-app
ENTRYPOINT []
