FROM golang:1.15.0-alpine3.12

RUN apk update upgrade
RUN apk add git build-base gcc

RUN go get -u github.com/golang/dep/cmd/dep
WORKDIR /go/src/github.com/CMSgov/bcda-ssas-app
COPY . .

RUN go get -u github.com/go-swagger/go-swagger/cmd/swagger
RUN dep ensure

WORKDIR /go/src/github.com/CMSgov/bcda-ssas-app/ssas/service/main
CMD ["swagger", "generate", "spec", "-i", "../../swaggerui/tags.yml", "-o", "../../swaggerui/swagger.json", "-m"]
