FROM golang:1.18.3-buster

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /go/src/github.com/CMSgov/bcda-ssas-app
COPY . .

RUN curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.12.0

RUN apt-get update

WORKDIR /go/src/github.com/CMSgov/bcda-ssas-app
ENTRYPOINT []
