FROM postman/newman
ARG CERT
RUN apt-get update && apt-get install -y ca-certificates
COPY $CERT /usr/local/share/ca-certificates/
RUN update-ca-certificates
WORKDIR /go/src/github.com/CMSgov/bcda-ssas-app/test/postman_test
COPY ./test/postman_test .
WORKDIR /go/src/github.com/CMSgov/bcda-ssas-app/
ENV NODE_OPTIONS "--max-old-space-size=2048"
ENTRYPOINT ["newman", "run", "--timeout-script", "99999"]
