#!/usr/bin/env bash
# A pre-commit hook which checks if any files need to be gofmt'd

# the following is based on: 
# https://github.com/golang/go/blob/release-branch.go1.1/misc/git/pre-commit

tmpfile=$(mktemp)
git diff --cached --name-only --diff-filter=ACM > $tmpfile

# Are there any added, copied, or modified .go files that are staged for commit?
gofiles=$(grep '.go$' < "$tmpfile")
[ -z "$gofiles" ] && exit 0

# Check if they need to be formatted
unformatted=$(gofmt -l "$gofiles")
[ -z "$unformatted" ] && exit 0

# Some files are not gofmt'd. Print message and fail.
echo >&2 "Go files must be formatted with gofmt. Please run:"
for fn in $unformatted; do
    echo >&2 "  gofmt -w $PWD/$fn"
done

exit 1
