name: "SSAS CI Workflow"

on: [push]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1
      - name: "Build the stack"
        run: |
          make docker-bootstrap
      - name: "Run all tests"
        run: |
          make test

  snyk:
    name: "Run Snyk Workflow"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: "Run Snyk"
      uses: snyk/actions/golang@master
      continue-on-error: false
      with:
        command: test
        args: --severity-threshold=high
    - name: Build Docker Image
      run: |
        docker build -f Dockerfiles/Dockerfile.package -t ssas-package .
        docker build -f Dockerfiles/Dockerfile.tests -t ssas-tests .
    - name: "Run Snyk - Docker/Package"
      uses: snyk/actions/docker@master
      continue-on-error: false
      with:
        image: ssas-package
        args: --file=Dockerfiles/Dockerfile.package --severity-threshold=high
    - name: "Run Snyk - Docker/Tests"
      uses: snyk/actions/docker@master
      continue-on-error: false
      with:
        image: ssas-tests
        args: --file=Dockerfiles/Dockerfile.tests --severity-threshold=high
