# This workflow generates database documentation and ERD files.
#
name: Generate dbdocs

on:
  pull_request:
    paths:
      - .github/workflows/dbdocs.yml
      - db/migrations

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: "Build the stack"
        run: |
          make docker-bootstrap

      - name: Generate DB docs
        run: make dbdocs

      - uses: EndBug/add-and-commit@v9
        with:
          add: dbdocs
          message: "Generate dbdocs"
          default_author: github_actions
