name: WAFSync Lambda prod deploy

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambda/wafsync
    environment: prod
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-prod-github-actions
      - name: Promote lambda code from test to prod
        run: |
          aws s3 cp --no-progress \
            s3://bcda-test-waf-sync-function/function-${{ github.sha }}.zip \
            s3://bcda-prod-waf-sync-function/function-${{ github.sha }}.zip
          aws lambda update-function-code --function-name bcda-prod-waf-sync \
            --s3-bucket bcda-prod-waf-sync-function --s3-key function-${{ github.sha }}.zip